### ISSUE TITLE
New questions to add

### ISSUE THREAD

**Issue by themg96** [theLeroy/EnergyAirHack2018#2]
See attached file
[addedquestions.txt](https://github.com/theLeroy/EnergyAirHack2018/files/2269909/addedquestions.txt)

**Comment by tobiasBlaser** [comment]
I got more new questions

`{
    frage:"welcherberühmtedj-actstand2017aufderbühnedesenergyair?",
    antwort:"dimitrivegas&likemike"
    },

    {
    frage:"welcheractstandbeimerstenenergyair2014undauchimletztenjahraufderbühne?",
    antwort:"pegasus"
    },
    
    {
        frage:"wiereistekygoimjahr2015ansenergyair?",
        antwort:"imprivatchat"
    },
    {
        frage:"woherkommtenergyairactmaxgiesinger?",
        antwort:"deutschland"
    },

    {
        frage:"aufwelchemwegkannmankeineenergyairticketsgewinnen?",
        antwort:"e-mail"
    },

    {
        frage:"aufwelchersocial-media-plattformkannmankeineenergyairticketsgewinnen?",
        antwort:"twitter"
    },

    {
        frage:"wieheisstderaktuellesommerhitvonenergyairactalvarosoler?",
        antwort:"lacintura"
    },

    {
        frage:"wennahmknackeboulamenergyair2014mitbackstage?",
        antwort:"seinmami"
    },

    {
        frage:"werspieltdiemuttervoncyril?",
        antwort:"ankeengelke"
    },
    {
        frage:"welchefarbehabendiehaaredessocialmediastarsjuliabeautximfilm?",
        antwort:"pink"
    },
    {
        frage:"waspassiertwennesameventtagregnet?",
        antwort:"energyairfindettrotzdemstatt"
    },
    {
        frage:"energyairistdereinzigeenergyevent,…?",
        antwort:"…derunterfreiemhimmelstattfindet."
    },
    {
        frage:"welcheractinterviewtevordemletztenenergyairdaspublikum?",
        antwort:"babashrimps"
    },
    {
        frage:"welchensongperformtedodoamenergyairmitdenüberraschungsgästenlo&leduc?",
        antwort:"füringwer&ewig"
    },
    {
        frage:"wievielespotlightsgibtesamenergyair?", //unsure
        antwort:"250"
    },
    {
        frage:"wievielekonfetti-kanonengibtesamenergyair?", //unsure
        antwort:"60"
    },
    {
        frage:"wasverlangtenenaamenergyair2016?",
        antwort:"einekomplettweissegarderobe"
    },
    {
        frage:"welcheamerikanischebandtratamenergyair2016auf?",
        antwort:"onerepublic"
    },
    {
        frage:"wievielemitarbeitersindamenergyairimeinsatz?", //unsure
        antwort:"1300"
    }`

**Comment by theLeroy** [comment]
Wow Very nice! Thanks allot but i have implemented the new questions on relese v1.2. Feal free to download the new version

**Comment by theLeroy** [comment]
Feal free to send me new questions if there are any changes. Just open a new issue. thx
