### ISSUE TITLE
Wrong answers

### ISSUE THREAD

**Issue by andibagandi** [theLeroy/EnergyAirHack2018#3]
thank you. exaclty what I was looking for.
- a couple answers are wrong. could be optimized.
- scripts run for 3 hours without success. Did someone win? Maybe you have to set a timeout after choosing a logo. Is it possible to win?

**Comment by theLeroy** [comment]
Hay
Witch answers are wrong? 

The winn rate is: 1 ticket all 15 minutes. Its very very very low

**Comment by kellerpius** [comment]
Meine Korrektur der Antworten
Zeile 115 die Bühne ist 450 Tonnen
Zeile 125 es gibt 250 Spotlights
Zeile 175 es war Jung verdammt
Zeile 180 es sind 1000 Mitarbeiter
Zeile 210 20 Kanonen
Zeile 215 um 17 Uhr

An dieser stelle auch meinen Herzlichen Dank für deine Arbeit

**Comment by theLeroy** [comment]
Oke i will fix it

**Comment by theLeroy** [comment]
@andibagandi @kellerpius I have fix the questions. New release is online. Thanks allot
