### ISSUE TITLE
Not all Questions are answered correctly

### ISSUE THREAD

**Issue by Laars1** [theLeroy/EnergyAirHack2018#4]
Hey, 
Mir isch ufgfaue das nid au frage richtig beantwortet si, ha es paar frage überarbeitet.

Hie dr Frage Array:
`_var fragen = [
  {
  frage:"wannfandenergyairzumerstenmalstatt?",
  antwort:"2014"
  },

  {
  frage:"wannistderoffiziellefilmstartvondasschönstemädchenderweltindenschweizerkinos?",
  antwort:"6.september2018"
  },
  {
  frage:"wereröffnetedasersteenergyair?",
  antwort:"bastianbaker"
  },
  {
  frage:"woerfährstduimmerdieneusteninfosrundumenergyair?",
  antwort:"imradio,aufderwebsiteundübersocialmedia"
  },
  {
  frage:"mitwelchempreiswurdedernachwuchsstarlunawedlerdiesesjahrausgezeichnet?",
  antwort:"shootingstarberlinale2018"
  },
  {
  frage:"werwarderletzteactbeimenergyair2017?",
  antwort:"kodaline"
  },
  {
  frage:"welchefussballmannschaftistimstadedesuissezuhause?",
  antwort:"bscyoungboys"
  },
  {
  frage:"welcherdieseractshatteeinenauftrittamenergyair2017?",
  antwort:"aloeblacc"
  },
  {
  frage:"wofindetdasenergyairstatt?",
  antwort:"stadedesuisse(bern)"
  },
  {
  frage:"wasistcyrilsbesonderebegabung?",
  antwort:"texteschreibenundrappen"
  },
  {
  frage:"werstandamletztenenergyairalsüberraschungsgastaufderbühne?",
  antwort:"bastianbaker"
  },

  {
  frage:"wievieleactswarenbeimletztenenergyairdabei?",
  antwort:"15"
  },

  {
  frage:"welcherschauspieler/rapperträgtimfilmeinegoldenemaske?",
  antwort:"cyril"
  },

  {
  frage:"mitwelchemdieserticketsgeniesstdudiebestesichtzurenergyairbühne?",
  antwort:"xtra-circle"
  },

  {
  frage:"wievieleenergyairticketswerdenverlost?",
  antwort:"40’000"
  },

  {
  frage:"diewievielteenergyairausgabefindetdiesesjahrstatt?",
  antwort:"dievierte"
  },

  {
  frage:"dasnrj-gefährtistein…",
  antwort:"tuktuk"
  },

  {
  frage:"wannfindetdasenergyair2018statt?",
  antwort:"8.september2018"
  },

  {
  frage:"energyairticketskannman…",
  antwort:"gewinnen"
  },

  {
  frage:"wasistcyrils(aaronhilmer)markenzeichenimfilm?",
  antwort:"seinegrossenase"
  },

  {
  frage:"welcherschweizershootingstarspieltindasschönstemädchenderweltdiehauptrolle?",
  antwort:"lunawedler"
  },

  {
  frage:"wieschweristdieenergyairbühne?",
  antwort:"1000tonnen"
  },
//New one
  {
  frage:"energyairistdereinzigeenergyevent,…",
  antwort:"…fürdenmanticketsnurgewinnenkann."
  },

  {
  frage:"wievielespotlightsgibtesamenergyair?",
  antwort:"250"
  },

  {
  frage:"welcheractstandbeimerstenenergyair2014undauchimletztenjahraufderbühne?",
  antwort:"pegasus"
  },

  {
  frage:"aufwelchersocial-media-plattformkannmankeineenergyairticketsgewinnen?",
  antwort:"twitter"
  },

  {
  frage:"wohinführtdieklassenfahrt?",
  antwort:"berlin"
  },

  {
  frage:"wiereistekygoimjahr2015ansenergyair?",
  antwort:"imprivatjet"
  },

  {
  frage:"wiebreitistdieenergyairbühne?",
  antwort:"70meter"
  },

  {
  frage:"woherkommtenergyairactmaxgiesinger?",
  antwort:"deutschland"
  },

  {
  frage:"welchefarbehabendiehaaredessocialmediastarsjuliabeautximfilm?",
  antwort:"pink"
  },

  {
  frage:"aufwelchemwegkannmankeineenergyairticketsgewinnen?",
  antwort:"e-mail"
  },

  {
  frage:"werspieltdiemuttervoncyril?",
  antwort:"ankeengelke"
  },

  {
  frage:"welchensongperformtedodoamenergyairmitdenüberraschungsgästenlo&leduc?",
  antwort:"mishuusdishuus"
  },

  {
  frage:"wievielemitarbeitersindamenergyairimeinsatz?",
  antwort:"1300"
  },

  {
  frage:"waspassiert,wennesameventtagregnet?",
  antwort:"energyairfindettrotzdemstatt"
  },

  {
  frage:"welcheamerikanischebandtratamenergyair2016auf?",
  antwort:"onerepublic"
  },

  {
  frage:"wieheisstderaktuellesommerhitvonenergyairactalvarosoler?",
  antwort:"lacintura"
  },

  {
  frage:"welcherberühmtedj-actstand2017aufderbühnedesenergyair?",
  antwort:"dimitrivegas&likemike"
  },

  {
  frage:"wasverlangtenenaamenergyair2016?",
  antwort:"einekomplettweissegarderobe"
  },

  {
  frage:"wievielekonfetti-kanonengibtesamenergyair?",
  antwort:"20"
  },

  {
  frage:"wannbeginntdasenergyair2018?",
  antwort:"um17uhr"
  },

  {
  frage:"welcheractinterviewtevordemletztenenergyairdaspublikum?",
  antwort:"babashrimps"
  },

  {
  frage:"wennahmknackeboulamenergyair2014mitbackstage?",
  antwort:"seinmami"
  }

];_`

Mercii füre Bot :)¨
Gruess Lars

**Comment by theLeroy** [comment]
Hay Perfekt file dank. Mis Problem isch so chli dasi ni gse was genau gendert hesch. Mach doch nechschtmau direket e pull request. Aber trozdem Merci merci und e schöne abe

**Comment by theLeroy** [comment]
Has kopiert und apast

**Comment by theLeroy** [comment]
New releas is online

**Comment by Laars1** [comment]
Ahh ja sorry, nächst mau machi e pull request
