### ISSUE TITLE
Some Question 

### ISSUE THREAD

**Issue by Rowside** [theLeroy/EnergyAirHack2018#5]
Hello i've download Your Bot and See Some Question  Are Wrong  so

I think about

Erster act 2014  is Bastian Baker not Pegasus 

And Überraschungsgast   same  Bastian Baker

And Energy  air Ist das Einzige event was untet Freien Himmel stadt findet

Have a nice day Bye

**Comment by theLeroy** [comment]
Oke i will change it

**Comment by theLeroy** [comment]
Hay @Rowside 

Ig weis ni öb dini lösig mit unter freiem Hîmmel stat findet richtig isch. Isch ja bi aune openairs so...

**Comment by Rowside** [comment]
ja aber Energy Fashion Night is ja auch im Hallenstadion und kann man auch Tickets Immer gewinnen, bzw Energy Air ist mir mehr bekannt wegen State De Suisse  und das ist ja ein Grosses Fussballstadion in der schwiez.

**Comment by Rowside** [comment]
Aber wenn gewünnt me be dim Bot öpis  Han jitze Ganzi Nacht la Düre Laufe

**Comment by themg96** [comment]
D Gwinnchance isch sehr chlii(all 15 Minute 1x 2 Tickets), dr Bot nimmt dr nume d Arbeit vom düreklicke ab. Ob eis gwinnsch oder vilech nie isch reine Zuefall @Rowside

**Comment by Rowside** [comment]
Hesch no e Fehler drine isch ds Fünfte nid DieVierte

**Comment by theLeroy** [comment]
New version 2.0v is online. I have change the releas system and added some questions
