### ISSUE TITLE
Frage wird nicht beantwortet

### ISSUE THREAD

**Issue by sapo01** [theLeroy/EnergyAirHack2018#8]
Bei der Frage, in welcher Stadt die Bad Spies keinen Halt machen, bleibt das Script hängen. 

Konkrete Frage:

Inn welches Haupstadt Europas machen die BAD SPIES keinen Halt?

Bern, Wien oder Rom zur Auswahl

**Comment by themg96** [comment]
Das Problem ist das Fragen hinzugefügt werden und Fragen verändert werden. Vermutlich gerade mit dem Ziel Bots zu schwächen @sapo01

**Comment by LukeZzzHD** [comment]
@sapo01 
Die Antwort wäre Bern, aber @themg96  hat recht...
Sie wissen dass viele Leute Automation verwenden und schwächen das so ab.

**Comment by theLeroy** [comment]
Wtf warum kein reCapcha. Einfach nur dumm. Sorry da muss man so was fast nutzen.

**Comment by theLeroy** [comment]
Hat es neue Fragen? Dann schickt mir doch die antworten oder Pullt mir ein Request. @sapo01 @themg96 @Rowside @LukeZzzHD
